version: '3'

services:
  zookeeper:
    image: 'bitnami/zookeeper'
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
    networks:
      - kafka-net
    volumes:
      - 'zookeeper_data:/bitnami'

  kafka:
    image: 'bitnami/kafka'
    container_name: kafka
    restart: always
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    ports:
      - '9092:9092'
    networks:
      - kafka-net
    volumes:
      - 'kafka_data:/bitnami'

  database:
    image: 'bitnami/postgresql'
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    networks:
      - kafka-net
    volumes:
      - 'postgres_data:/bitnami'

networks:
  kafka-net:

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  postgres_data:
    driver: local
